### ISSUE TITLE
Dead link for Miningzinc repository

### ISSUE THREAD

**Issue by LucFontaine** [MiniZinc/minizinc.github.io#15]
During the installation of miningzinc (http://inductiveconstraints.eu/miningzinc/) it is interrupt because :
repository 'https://www.minizinc.org/repos/libminizinc/' not found (dead link)

**Comment by guidotack** [comment]
That repository hasn't been live for a long time. Please contact the MiningZinc maintainers (this code was produced by a different team, not us).

**Comment by LucFontaine** [comment]
Thank you

**Comment by tias** [comment]
I'm a bit late to the party, but: that same repository is now hosted at https://github.com/MiniZinc/libminizinc.git

Replacing the URL in the MiningZinc installer by this one will get you a bit further. However, compilation of the specific needed commit of libmzn fails on my machine due to 'ceil' and 'floor' not being declared, e.g. more strict compiler checks. Using later commits may break other things : (
